#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

# Universal by default: a plain `swift build` produces a host-only binary, so
# building on Apple Silicon shipped an arm64 slice that Intel Macs cannot run at
# all. Set TOKENISLAND_HOST_ONLY=1 for a faster host-arch build while iterating.
if [ "${TOKENISLAND_HOST_ONLY:-0}" = "1" ]; then
  ARCH_FLAGS=()
  echo "Building host-arch only (TOKENISLAND_HOST_ONLY=1) — not for release."
else
  ARCH_FLAGS=(--arch x86_64 --arch arm64)
fi

swift build -c release "${ARCH_FLAGS[@]}"
BUILD_DIR="$(swift build -c release "${ARCH_FLAGS[@]}" --show-bin-path)"

APP_DIR="$ROOT_DIR/.build/TokenIsland.app"
CONTENTS_DIR="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"

rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
cp "$BUILD_DIR/TokenIsland" "$MACOS_DIR/TokenIsland"
if [ -d "$BUILD_DIR/TokenIsland_TokenIslandKit.bundle" ]; then
  cp -R "$BUILD_DIR/TokenIsland_TokenIslandKit.bundle" "$RESOURCES_DIR/"
fi
if [ -d "$ROOT_DIR/Docs" ]; then
  cp -R "$ROOT_DIR/Docs" "$RESOURCES_DIR/Docs"
fi

# App icon (pixel-pet crab). Tolerate failure — the bundle works without it.
if ! swift "$ROOT_DIR/Scripts/generate_app_icon.swift"; then
  echo "warning: app icon generation failed; bundling without AppIcon.icns" >&2
fi
if [ -f "$ROOT_DIR/.build/AppIcon.icns" ]; then
  cp "$ROOT_DIR/.build/AppIcon.icns" "$RESOURCES_DIR/AppIcon.icns"
fi

# Sparkle.framework has to live inside the bundle for the app to launch, and it
# carries its own XPC services and Updater.app that must be signed individually
# (Xcode does this via "Embed Frameworks"; here it is explicit).
SPARKLE_FRAMEWORK="$(/usr/bin/find "$ROOT_DIR/.build/artifacts" -type d -name "Sparkle.framework" -path "*macos*" 2>/dev/null | head -1)"
if [ -n "$SPARKLE_FRAMEWORK" ]; then
  mkdir -p "$CONTENTS_DIR/Frameworks"
  rm -rf "$CONTENTS_DIR/Frameworks/Sparkle.framework"
  cp -R "$SPARKLE_FRAMEWORK" "$CONTENTS_DIR/Frameworks/"
  echo "Embedded Sparkle.framework"
else
  echo "warning: Sparkle.framework not found — run 'swift build' first; updates will not install in place" >&2
fi

cat > "$CONTENTS_DIR/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>TokenIsland</string>
  <key>CFBundleIdentifier</key>
  <string>com.tokenisland.app</string>
  <key>CFBundleName</key>
  <string>TokenIsland</string>
  <key>CFBundleDisplayName</key>
  <string>TokenIsland</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <!-- macOS shows this in the Automation prompt, and refuses to send Apple
       Events at all when it is missing — click-to-jump drives Terminal and
       iTerm2 through AppleScript. -->
  <key>NSAppleEventsUsageDescription</key>
  <string>TokenIsland controls your terminal apps (Terminal, iTerm2) to jump to the exact window, tab, and split pane of the session you click in the notch.</string>
  <!-- Sparkle-format release feed. The app checks it on launch and hourly;
       a build without this key reports "no release feed" instead of
       pretending to be up to date. -->
  <!-- Sparkle verifies every download against this EdDSA public key before
       installing. The private half lives in the release machine's keychain
       (generated by Sparkle's generate_keys) and is never in the repo. -->
  <key>SUPublicEDKey</key>
  <string>SsUkhESx4f1VaQjtAEdxkmZvPKh8lBn04D+E/LEJmVo=</string>
  <key>SUEnableInstallerLauncherService</key>
  <false/>
  <key>SUFeedURL</key>
  <string>https://github.com/rmm-code/tokenisland/releases/latest/download/appcast.xml</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>CFBundleShortVersionString</key>
  <string>__TI_VERSION__</string>
  <key>CFBundleVersion</key>
  <string>__TI_BUILD__</string>
  <!-- Must match Package.swift's .macOS(.v14); 14.6 here silently locked out
       every 14.0–14.5 Mac the package itself claims to support. -->
  <key>LSMinimumSystemVersion</key>
  <string>14.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright 2026 TokenIsland</string>
</dict>
</plist>
PLIST

# Release builds pass a version in; local builds keep the development one.
TI_VERSION="${TOKENISLAND_VERSION:-0.1.0}"
TI_BUILD="${TOKENISLAND_BUILD:-$(date +%Y%m%d%H%M)}"
/usr/bin/sed -i '' "s/__TI_VERSION__/$TI_VERSION/; s/__TI_BUILD__/$TI_BUILD/" "$CONTENTS_DIR/Info.plist"

# macOS ties Keychain "Always Allow" grants and TCC permissions (Accessibility,
# Automation) to the app's code identity. An ad-hoc signature has none, so every
# rebuild looks like a different app and every grant is asked for again. Sign
# with a real identity when there is one — see Scripts/create_signing_identity.sh.
# Preference order: an explicit override, then a real Apple identity already in
# the keychain (best — stable Team ID), then the local self-signed fallback.
IDENTITY="${TOKENISLAND_SIGN_IDENTITY:-}"
if [ -z "$IDENTITY" ]; then
  IDENTITIES="$(security find-identity -v -p codesigning 2>/dev/null || true)"
  for pattern in "Developer ID Application" "Apple Development" "TokenIsland Dev"; do
    match="$(printf '%s\n' "$IDENTITIES" | grep -m1 "$pattern" || true)"
    if [ -n "$match" ]; then
      # find-identity prints:  1) <SHA1> "Name (TEAMID)"
      IDENTITY="$(printf '%s\n' "$match" | sed -E 's/^[^"]*"(.*)"$/\1/')"
      break
    fi
  done
fi

ENTITLEMENTS="$ROOT_DIR/Scripts/TokenIsland.entitlements"

if [ -n "$IDENTITY" ]; then
  # Hardened runtime is required for notarization, and it blocks Apple Events
  # unless the entitlement is present — without it click-to-jump dies on every
  # distributed build.
  # Notarization requires a secure timestamp from Apple's server; local builds
  # skip it so an offline rebuild still works.
  case "$IDENTITY" in
    "Developer ID Application"*) TIMESTAMP_FLAG="--timestamp" ;;
    *) TIMESTAMP_FLAG="--timestamp=none" ;;
  esac
  # Inside-out: nested code must be signed before whatever contains it, or the
  # outer signature seals a stale hash. `--deep` cannot be trusted for Sparkle's
  # XPC services and Updater.app, which need their own identifiers preserved.
  SPARKLE_IN_BUNDLE="$CONTENTS_DIR/Frameworks/Sparkle.framework"
  if [ -d "$SPARKLE_IN_BUNDLE" ]; then
    while IFS= read -r nested; do
      [ -n "$nested" ] || continue
      codesign --force --sign "$IDENTITY" --options runtime "$TIMESTAMP_FLAG" "$nested"
    done < <(
      /usr/bin/find "$SPARKLE_IN_BUNDLE" \
        \( -name "*.xpc" -o -name "*.app" -o -name "Autoupdate" -o -name "*.dylib" \) \
        -maxdepth 4 2>/dev/null
    )
    codesign --force --sign "$IDENTITY" --options runtime "$TIMESTAMP_FLAG" "$SPARKLE_IN_BUNDLE"
  fi

  codesign --force --sign "$IDENTITY" \
    --identifier com.tokenisland.app \
    --options runtime \
    --entitlements "$ENTITLEMENTS" \
    "$TIMESTAMP_FLAG" \
    "$APP_DIR"
  echo "Signed with identity: $IDENTITY (hardened runtime, permission grants persist)"
else
  codesign --force --deep --sign - --identifier com.tokenisland.app "$APP_DIR"
  echo "Signed ad-hoc — macOS will re-ask for Keychain/Accessibility after every rebuild."
  echo "Run  bash Scripts/create_signing_identity.sh  once to stop that."
fi

echo "Created $APP_DIR"
echo "Run it with:  open '$APP_DIR'"
echo "(Grant Accessibility once: System Settings → Privacy & Security → Accessibility → TokenIsland)"
